server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: estudiantes
          uri: lb://estudiantes
          predicates:
            - Path=/api/estudiantes/**
        - id: cursos
          uri: lb://cursos
          predicates:
            - Path=/api/cursos/**
        - id: kafka
          uri: lb://kafka
          predicates:
            - Path=/api/kafka/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/